### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DarkSkull91** [ziplokk1/incapsula-cracker#7]
I tried to use this script but I get this error:

```
> Traceback (most recent call last):
  File "incapsula-example.py", line 6, in <module>
    response = crack(session, response)  # url is no longer blocked by incapsula
  File "C:\Program Files\Python 2.7\lib\site-packages\incapsula\requests_.py", line 65, in crack
    _load_encapsula_resource(sess, response)
  File "C:\Program Files\Python 2.7\lib\site-packages\incapsula\requests_.py", line 18, in _load_encapsula_resource
    code = get_obfuscated_code(response.content)
  File "C:\Program Files\Python 2.7\lib\site-packages\incapsula\methods.py", line 136, in get_obfuscated_code
    return code[0]
IndexError: list index out of range
```

**Comment by ziplokk1** [comment]
Please look [here](https://github.com/ziplokk1/incapsula-cracker-py3) and see if that fixes your issue. If there is still an issue, open an issue in the new repository.

Thank you
